### ISSUE TITLE
Default branch should be `main`

### ISSUE THREAD

**Issue by joffrey-bion** [xvik/gradle-github-info-plugin#1]
The default branch for `GithubInfoExtension.rawFileUrl` is `master` but the default on GitHub now is `main`.

The `LicenseHelper` generates the default license URL using the raw file URL to the locally found `LICENSE` file, without branch parameter.
We could make the default branch of the repository configurable in the extension, and use that in `lookupLicenseFile` instead of using the default value for the branch argument (or even better, make the branch argument of `rawFileUrl` default to the value of that new `defaultBranch` property).

The default for the new property could be `master` for backwards compatibility, but it would be nice if it were `main` instead, given the new GitHub defaults.

**Comment by xvik** [comment]
What if I use `HEAD` for default files branch. In this case file links would work in all cases ([for example, project license link](https://raw.githubusercontent.com/xvik/gradle-github-info-plugin/HEAD/LICENSE))?

I'll add new branch property with the default to HEAD and user would be able to change it, if required. By default, this would work for both types of repositories (for example, I still use master even for new repositories) - looks like a good default.

**Comment by joffrey-bion** [comment]
Wow, I didn't expect `HEAD` to make any sense in GitHub's URLs, but it does seem to work indeed. Good point.
Note that in the comments of [this SO thread](https://stackoverflow.com/questions/64726262/is-there-a-stable-url-to-always-get-the-default-branch-in-github), they also mention using `-` which would actually redirect to the true default branch URL instead of a fixed commit hash that corresponds to the current latest commit of the default branch. It depends on what we want though. Also, `-` doesn't work in all places expecting a branch, while `HEAD` does. Up to you, really.

I still believe it would be worth having a `defaultBranch` configuration property that defaults to `main`, because that's how Github works, and some plugins that use information from this github-info plugin might need actual branch names. But your solution is a good pragmatic option to main backwards compat with previous projects, at least regarding this license file URL.

**Comment by xvik** [comment]
> Note that in the comments of [this SO thread](https://stackoverflow.com/questions/64726262/is-there-a-stable-url-to-always-get-the-default-branch-in-github), they also mention using - which would actually redirect to the true default branch

I like auto default branch (`-`), but, unfortunately, it works only for blob links (not direct file link): 
https://github.com/xvik/gradle-github-info-plugin/blob/-/LICENSE

And does not for direct links:
https://raw.githubusercontent.com/xvik/gradle-github-info-plugin/-/LICENSE

Besides, direct link with head would not redirect to commit hash, just serve required file:
https://raw.githubusercontent.com/xvik/gradle-github-info-plugin/HEAD/LICENSE

>I still believe it would be worth having a defaultBranch configuration property that defaults to main, because that's how Github works

I don't think many people use this plugin at all :) There would be a new `branch` property and so the ability to change default. With 'main' as default I would have to change it in all my repos - I would like to avoid this redundant step as long as head deafult would not harm users with 'main' branch (compromise)

**Comment by xvik** [comment]
I will release new version today

**Comment by joffrey-bion** [comment]
Thanks a lot for the quick release. I'm a bit surprised by the specificity of the `branch` property description. I thought it was supposed to define the *default branch* selected in GitHub (in general). That's why I had suggested the name `defaultBranch` - it's the default branch of the repository. It could theoretically be used for anything, not just as a default for file links. But maybe I'm splitting hair here.

In any case, thanks again. With the HEAD default I can forget about it anyway.
